//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion_Mensual_Detalle
    {
        public int Id_Detalle { get; set; }
        public int Liquidacion_Id { get; set; }
        public int Empleado_Id { get; set; }
        public int Concepto_Id { get; set; }
        public int Monto { get; set; }
    

        public virtual Concepto Concepto { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Liquidacion_Mensual Liquidacion_Mensual { get; set; }
    }
}
